name: Deploy snapshot
on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 17
        distribution: 'adopt'
        server-id: nexus # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: ${{ secrets.NEXUS_USERNAME }} # env variable for username in deploy
        server-password: ${{ secrets.NEXUS_PASS }} # env variable for token in deploy
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }} # env variable for GPG private key passphrase
      - name: Publish package
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASS }}