name: Deploy snapshot
on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'adopt'
          server-id: nexus # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: ${{ secrets.NEXUS_USERNAME }} # env variable for username in deploy
          server-password: ${{ secrets.NEXUS_PASS }} # env variable for token in deploy
      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASS }}
        run: |
          echo $MAVEN_USERNAME
          mvn \
          deploy \
          -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
