name: Create release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version for the release. Format eg 1.0.1"
        required: true
      developmentVersion:
        description: "Next development version. Format eg 1.0.1"
        required: true

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "master"
      - run: export MAVEN_OPTS="--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          server-id: nexus # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Configure Git
        run: |
          git config --global user.email "github@actions.com"
          git config --global user.name "Github Actions"
      - name: Publish new release
        run: |
          mvn release:prepare release:perform \
          "-DgenerateBackupPoms=false -Dtag=v$releaseVersion -DreleaseVersion=$releaseVersion -DdevelopmentVersion=$developmentVersion-SNAPSHOT"
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.NEXUS_PASS }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}